# Generated by Django 3.1.7 on 2021-04-28 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacultySpecializations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnp', models.IntegerField()),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('dateOfBirth', models.DateField()),
                ('placeOfBirth', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('lastNameFather', models.CharField(max_length=15)),
                ('lastNameMother', models.CharField(max_length=15)),
                ('motherProfession', models.CharField(max_length=25)),
                ('fatherProfession', models.CharField(max_length=25)),
                ('fatherPhoneNumber', models.CharField(max_length=15)),
                ('motherPhoneNumber', models.CharField(max_length=15)),
                ('facultyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.faculty')),
                ('specializationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.facultyspecializations')),
            ],
        ),
    ]
