# Generated by Django 3.1.7 on 2021-04-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty',
            table='Faculty',
        ),
        migrations.AlterModelTable(
            name='facultyspecializations',
            table='FacultySpecializations',
        ),
        migrations.AlterModelTable(
            name='students',
            table='Students',
        ),
    ]
