# Generated by Django 3.1.7 on 2021-04-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20210428_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='dateOfBirth',
            new_name='DoB',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='placeOfBirth',
            new_name='PoB',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='id',
        ),
        migrations.RemoveField(
            model_name='facultyspecializations',
            name='id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facultyspecializations',
            name='spec_name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='cnp',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
