# Generated by Django 3.1.7 on 2021-05-12 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_auto_20210428_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffType',
            fields=[
                ('ID', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'StaffType',
            },
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='faculty_name',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='facultyspecializations',
            old_name='spec_name',
            new_name='ID',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='adress',
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('cnp', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('DoB', models.DateField()),
                ('PoB', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('lastNameFather', models.CharField(max_length=15)),
                ('lastNameMother', models.CharField(max_length=15)),
                ('dateOfHiring', models.DateField()),
                ('salary', models.IntegerField()),
                ('yearsOfService', models.IntegerField()),
                ('speciality', models.CharField(max_length=35)),
                ('facultyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.faculty')),
                ('specializationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.facultyspecializations')),
                ('staffLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.stafftype')),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
    ]
