# Generated by Django 3.1.7 on 2021-05-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20210512_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='adress',
            field=models.CharField(default='', max_length=50),
        ),
    ]
