# Generated by Django 3.1.7 on 2021-05-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_faculty_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='DoB',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='PoB',
            new_name='placeOfBirth',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='DoB',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='PoB',
            new_name='placeOfBirth',
        ),
    ]
