# Generated by Django 3.1.7 on 2021-05-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_auto_20210512_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='placeOfBirth',
            new_name='DoB',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='dateOfBirth',
            new_name='PoB',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='dateOfBirth',
            new_name='DoB',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='placeOfBirth',
            new_name='PoB',
        ),
    ]
